### PR TITLE
Fix minor issues in ABI conversions.

### LINKED ISSUE #376: Support abi conversion of declarations.
Declarations are currently skipped, since I was running into errors when trying to figure out location information for arguments. This should not be a hard thing to finish implementing - basically only the type needs to be changes, there is no need to emit prologues or epilogues as the function is without body.

### PR DESCRIPTION
**Pull request by lkorenc**
closes #376 and fixes incorrect name prefix during abi conversions.

### CODE REVIEW

File: test/vast/Compile/SingleSource/puts-a.c [hunk 1]
```diff
@@ -1,5 +1,4 @@
-// RUN: %vast-front -o %t %s && %t hello | %file-check %s
```
Comment (xlauko) [inline test/vast/Compile/SingleSource/puts-a.c:1]: `-vast-pipeline=with-abi` should not exists anymore?

**Comment by lkorenc** [comment]
close #388

File: lib/vast/Conversion/ABI/EmitABI.cpp [hunk 2]
```diff
@@ -227,7 +227,7 @@ namespace vast
                         op.getLoc(),
                         // Temporal, to avoid verification issues, will be changed once
                         // original func is removed.
-                        "vast.abi" + op.getName().str(),
+                        "vast.abi." + op.getName().str(),
```
Comment (xlauko) [inline lib/vast/Conversion/ABI/EmitABI.cpp:230]: make this some global named constant `vast::abi_prefix`, it is already on two places

**Review by xlauko — APPROVED** [review]
