### PR TITLE
util: Clean up and fix UB in `VAST_[CHECK,ASSERT,UNREACHABLE]` macros.

### LINKED ISSUE #483: Properly distinguish between `CHECK` and `ASSERT` macros.
### Prerequisites

- [X] I have read the documentation and the proposed feature is not implemented.

### Description

Currently everything is sinked to the `VAST_UNREACHABLE` which however behaves differently in debug vs release. Draw proper line between runtime and defensive checks and assure they behave as expected in different build types.

### PR DESCRIPTION
**Pull request by lkorenc**
closes #483

### CODE REVIEW

File: include/vast/Util/Warnings.hpp [hunk 1]
```diff
@@ -85,32 +85,51 @@ namespace vast {
...
+    #define VAST_UNIMPLEMENTED_MSG(msg) \
+        VAST_FATAL("not implemented: {0} because {1}", __PRETTY_FUNCTION__, msg)
 
-    #define VAST_TODO(fmt, ... ) VAST_UNREACHABLE("[vast-todo]: " # fmt __VA_OPT__(,) __VA_ARGS__ )
+    #define VAST_UNIMPLEMENTED_IF(cond) \
+        if (cond) { VAST_FATAL("not implemented: {0}", __PRETTY_FUNCTION__); }
+
+
+    #define VAST_TODO(fmt, ... ) \
+        VAST_FATAL("[Vast TODO]: " # fmt __VA_OPT__(,) __VA_ARGS__ )
```
Comment (xlauko) [inline include/vast/Util/Warnings.hpp:121]:
```suggestion
        VAST_FATAL("[VAST TODO]: " # fmt __VA_OPT__(,) __VA_ARGS__ )
```

for consistency

**Review by xlauko — APPROVED** [review]
