### PR TITLE
Fix type assertion due to invalid cast

### LINKED ISSUE #171: Type Assertion due to invalid cast
I see type assertion due to invalid cast from NamedType to FunctionType. It happens because typedef is getting lowered as NamedType. The issue can be reproduce with the code:

```
typedef int function_type(int a, int b);
function_type *p[2];
int test_func(void) {
  return p[1](15, 20);
}
```
https://github.com/trailofbits/vast/blob/master/lib/vast/Dialect/HighLevel/HighLevelTypes.cpp#L18
https://github.com/trailofbits/vast/blob/master/lib/vast/Dialect/HighLevel/HighLevelTypes.cpp#L23

### PR DESCRIPTION
**Pull request by xlauko**
- implements `getFunctionType` for typedef of function pointers. 
- updates `IndirectCallOp` to allow typedef `callee` type.

closes #171

### CODE REVIEW

File: include/vast/Dialect/HighLevel/HighLevelTypes.hpp [hunk 1]
```diff
@@ -157,8 +159,15 @@ namespace vast::hl
...
-    mlir::FunctionType getFunctionType(mlir::Type functionPointer);
+    mlir::FunctionType getFunctionType(Type function_pointer, Module mod);
+
+    mlir::FunctionType getFunctionType(Value callee);
+    mlir::FunctionType getFunctionType(mlir::CallOpInterface call);
+    mlir::FunctionType getFunctionType(mlir::CallInterfaceCallable callee, Module mod);
+    mlir::FunctionType getFunctionType(mlir::CallInterfaceCallable callee, Module mod);
+
+    Type getTypedefType(TypedefType type, Module mod);
+    Type getBottomTypedefType(TypedefType def, Module mod);
```
Comment (lkorenc) [inline include/vast/Dialect/HighLevel/HighLevelTypes.hpp:170]: What does `Bottom` mean here? The first type that is not typedef anymore? Add doc.

File: include/vast/Dialect/HighLevel/HighLevelTypes.hpp [hunk 2]
```diff
@@ -157,8 +159,15 @@ namespace vast::hl
...
     }
 
-    mlir::FunctionType getFunctionType(PointerType functionPointer);
-    mlir::FunctionType getFunctionType(mlir::Type functionPointer);
+    mlir::FunctionType getFunctionType(Type function_pointer, Module mod);
+
+    mlir::FunctionType getFunctionType(Value callee);
+    mlir::FunctionType getFunctionType(mlir::CallOpInterface call);
+    mlir::FunctionType getFunctionType(mlir::CallInterfaceCallable callee, Module mod);
+    mlir::FunctionType getFunctionType(mlir::CallInterfaceCallable callee, Module mod);
```
Comment (lkorenc) [inline include/vast/Dialect/HighLevel/HighLevelTypes.hpp:167]:
```suggestion
```

Looks like copy and paste error?

File: lib/vast/Dialect/HighLevel/HighLevelTypes.cpp [hunk 3]
```diff
@@ -29,19 +30,70 @@ namespace vast::hl
...
-            return getFunctionType(ty.getElementType());
+            return getFunctionType(ty.getElementType(), mod);
         if (auto ty = type.dyn_cast< PointerType >())
-            return getFunctionType(ty.getElementType());
+            return getFunctionType(ty.getElementType(), mod);
+        if (auto ty = type.dyn_cast< TypedefType >()) {
+            return getFunctionType(getTypedefType(ty, mod), mod);
+        }
+
+        type.dump();
```
Comment (lkorenc) [inline lib/vast/Dialect/HighLevel/HighLevelTypes.cpp:67]:
```suggestion
```

Forgotten debug print? Or is that supposed to be part of report if `UNREACHABLE` is reached?

**Review by lkorenc — APPROVED** [review]

File: include/vast/Dialect/HighLevel/HighLevelTypes.hpp (hunk 1 above)
Comment (xlauko) [reply include/vast/Dialect/HighLevel/HighLevelTypes.hpp:170]: Yes it unwraps all typedefs, do you have a better name?

Comment (lkorenc) [reply include/vast/Dialect/HighLevel/HighLevelTypes.hpp:170]: Nope, I guess just add a comment in case someone is confused when reading it?
